<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-11T09:53:51</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>adca9010-3de7-465d-b86c-a756820dcfe4</testSuiteGuid>
   <testCaseLink>
      <guid>655ba3fe-b471-4b0b-a99e-9d91f7ff5362</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginValidation/ValidateLoginWithInvalidData</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc567ae-6da5-4262-9009-0b43e106bbc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cb7ce61-3f30-45c2-9d8c-487edc5b53be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ead0ee7-8f86-4bd3-8070-3a8463d51d5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7a0e767-d461-43a5-9345-6af3de97e992</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginValidation/ValidatetheLogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72f276e5-0d7f-4e14-80f2-7e94f5b45421</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40cad379-60be-4435-8b36-e03db127694b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
